# version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:$POSTGRES_PORT
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - link-shortener
      - db

  app:
    build: .
    depends_on:
      - db
    container_name: link-shortener-server
    restart: unless-stopped
    ports:
      - 3000:$PORT
    environment:
      - DATABASE_URL=$DATABASE_URL
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_ACCESS_KEY_ID=$CLOUDFLARE_ACCESS_KEY_ID
      - CLOUDFLARE_ACCESS_SECRET_KEY=$CLOUDFLARE_ACCESS_SECRET_KEY
      - CLOUDFLARE_BUCKET_NAME=$CLOUDFLARE_BUCKET_NAME
      - CLOUDFLARE_BUCKET_PUBLIC_URL=$CLOUDFLARE_BUCKET_PUBLIC_URL
    networks:
      - link-shortener

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    depends_on:
      - db
    command: ['npm', 'run', 'db:migrate']
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - CLOUDFLARE_ACCESS_KEY_ID=${CLOUDFLARE_ACCESS_KEY_ID}
      - CLOUDFLARE_ACCESS_SECRET_KEY=${CLOUDFLARE_ACCESS_SECRET_KEY}
      - CLOUDFLARE_BUCKET_NAME=${CLOUDFLARE_BUCKET_NAME}
      - CLOUDFLARE_BUCKET_PUBLIC_URL=${CLOUDFLARE_BUCKET_PUBLIC_URL}
    networks:
      - link-shortener

volumes:
  db:
    driver: local

networks:
  link-shortener:
    driver: bridge
  db:
    driver: bridge
